name: CI
on: [push, pull_request]

jobs:
  test-miner-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Run miner applications tests
        run: cargo test --verbose

  integration-test:
    if: github.event_name == 'pull_request'
    needs: test-miner-apps
    uses: GitGab19/sv2-integration-test-framework/.github/workflows/test-with-branch.yml@main
    with:
      repo_name: "sv2-miner-apps-test"
      branch_name: ${{ github.head_ref }}
